name: Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18.7.2'

      - name: Install dependencies
        run: npm install

      - name: Build and Deploy
        env:
          API_KEY: ${{ secrets.API_KEY }}
        run: |
          # Replace placeholders in your code with the secret
          sed -i 's/REPLACE_WITH_API_KEY/'"$API_KEY"'/g' config.js
          
          # Build and deploy your website
          npm run build
          npm run deploy
